tap_install:
  values:
    shared:
      ingress_domain: tap.run-yellow.xploretanzu.com
      ingress_issuer: ""
    
    ceip_policy_disclosed: true
    profile: run

    supply_chain: basic

    appliveview_connector:
      backend:
        ingressEnabled: true
        sslDeactivated: false
        host: appliveview.tap.view-green.xploretanzu.com

    contour:
      infrastructure_provider: aws
      envoy:
        service:
          type: LoadBalancer

    namespace_provisioner:
      controller: true

    api_auto_registration: 
      tap_gui_url: https://tap-gui.tap.view-green.xploretanzu.com
      cluster_name: run-green
