tap_install:
  values:
    shared:
      ingress_domain: tap.view-green.xploretanzu.com
    ceip_policy_disclosed: true
    profile: view

    accelerator:
      ingress:
        include: true
        enable_tls: false

    appliveview:
      ingressEnabled: true

    tap_gui:
      service_type: ClusterIP
      # metadataStoreAutoconfiguration: true
      app_config:
        catalog:
          locations:
          - type: url
            target: https://github.com/dipalpat/git-catalog/blob/main/catalog-info.yaml
        backend:
          reading:
            allow:
            - host: github.com


    contour:
      infrastructure_provider: aws
      envoy:
        service:
          type: LoadBalancer
    