# tap_install:
#   values:
    shared:
      ingress_domain: tap.view-green.xploretanzu.com
    ceip_policy_disclosed: true
    profile: view

    accelerator:
      ingress:
        include: true
        enable_tls: false

    appliveview:
      ingressEnabled: true

    tap_gui:
      service_type: ClusterIP
      metadataStoreAutoconfiguration: true
      app_config:
        catalog:
          locations:
          - type: url
            target: https://github.com/dipalpat/git-catalog/blob/main/catalog-info.yaml
        backend:
          reading:
            allow:
            - host: github.com
        kubernetes:
          serviceLocatorMethod:
            type: 'multiTenant'
          clusterLocatorMethods:
            - type: 'config'
              clusters:
              ## build-green
                - name: build-green
                  authProvider: serviceAccount                  
                  skipTLSVerify: true
                  skipMetricsLookup: true
                  url: https://afb20561a5c4d4236a5f5eb86a85f37e-817718550.us-east-2.elb.amazonaws.com
                  serviceAccountToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImZkQlFBUFczbWtSSW1wUDZvZ1ZBWmwwZXFrZ2NFWWxFSFpabHlZT0NBcW8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0YXAtZ3VpIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNTA1OWViZDQtZTc3MS00YjhiLWJkN2QtY2YzNWVkMjIzYzA4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRhcC1ndWk6dGFwLWd1aS12aWV3ZXIifQ.nur7jVtTxbq2C02zYcXlFRghv04JAbDkfmDsJ2VJCXIx07F7sdhGjrgXM84TAAPqvpXSbdeOCI81DtA4hLHQHwf8BsaBAX1X9mp3MGpHvIlBm_pofCigT7GbQxKin5pXRDht6DWFmLiaqAuWH8HCZmxrGJ_WuAwisEEBkr7tvdmanN_CowoRLKT8PYYINE8kbah_FC9LjmWRY7Nfi-HVXjVmV4rhfCIQWEor0FB7gfBBAfKYo09Z1Kx_ABXWj9BRjRXmcsXJ0Z2M4jlbkZKvaOeMfECkIDabV5t-Trq1pOJ8Req6C1Ik4hulF4ZRKX-H-aC3dQEXVMQ1q-2JtpHJCA"
              ## run-green
                - name: run-green
                  authProvider: serviceAccount            
                  skipTLSVerify: true
                  skipMetricsLookup: true
                  url: https://a7257082d32f2421ab2b0edc6204507e-318081447.us-east-2.elb.amazonaws.com
                  serviceAccountToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IkI4MUVGMU1vMzc3dTZzY2dBcHBGdHpVUFIwM3RhY0hJS1pITWl3MHFITUkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0YXAtZ3VpIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiODA0ODAyZTUtYWExZC00MTcwLWE0ZWEtMTFkZWNkZWMxZjNlIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRhcC1ndWk6dGFwLWd1aS12aWV3ZXIifQ.r0cWogi9w3rWymXpNDXQaHaDD7BVLCqivPNlcv4z2uh9EzwSlVNRpmcMGHc71VaEQ534Pj15vz-AH8PeAj1ruZqfZwYmgXc6UxSaAj2KQgBBTAmJS4u3iK-MfERL2z-NE2Af5q1IWcW72pTlso4jWmBNk6m48D660y3-_qhxnrLZoylhfBDgm1iMZFQg8pz3I54SjqReutZQVWRoBNVXfpjH9cIALMxulcEmvVrtc9fcrDqeem8sR0nRElfNESAX5VmrO9kH1zm6Wrc27aEMTLOzWTpjc-scjz4SjRuj5zva_1rvzgk5fOKJaz5tVDOtcQEUIMjgk7qMUDBNsBT5YA"

    contour:
      infrastructure_provider: aws
      envoy:
        service:
          type: LoadBalancer
    

